import type { MarketplaceOverview, Product, ProductCategory } from './types/index.js';

/** Product-type image pools (Unsplash). Used so tees don’t show landscapes, etc. */
const MEDIA = {
  tee: [
    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=900&q=80',
  ],
  hoodie: [
    'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1578587018452-892baccfd074?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1618354691438-25bc04584c23?auto=format&fit=crop&w=900&q=80',
  ],
  jersey: [
    'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
  ],
  poster: [
    'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=900&q=80',
  ],
  deskmat: [
    'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1593640408182-1274af8756db?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80',
  ],
  controller: [
    'https://images.unsplash.com/photo-1605901309584-818e25960a8f?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1612287230202-1ff1d867d530?auto=format&fit=crop&w=900&q=80',
  ],
  console: [
    'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1486572788966-cfd3df93f05d?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&w=900&q=80',
  ],
  statue: [
    'https://images.unsplash.com/photo-1608889175123-8ee362201f81?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80',
  ],
  mug: [
    'https://images.unsplash.com/photo-1514228742587-6ac3302c5cf4?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=900&q=80',
  ],
  hat: [
    'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?auto=format&fit=crop&w=900&q=80',
  ],
  keycap: [
    'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=80',
  ],
  cable: [
    'https://images.unsplash.com/photo-1625948515291-69613efd103f?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=900&q=80',
  ],
  light: [
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80',
  ],
  jacket: [
    'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1548126032-079a0fb0099d?auto=format&fit=crop&w=900&q=80',
  ],
  bag: [
    'https://images.unsplash.com/photo-1544816155-12df9643f667?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=80',
  ],
  collectible: [
    'https://images.unsplash.com/photo-1608889175123-8ee362201f81?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=900&q=80',
  ],
  notebook: [
    'https://images.unsplash.com/photo-1531346878377-a5be20836c33?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=900&q=80',
  ],
  stand: [
    'https://images.unsplash.com/photo-1593640408182-1274af8756db?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=900&q=80',
  ],
  default: [
    'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80',
  ],
} as const;

type MediaKind = keyof typeof MEDIA;

/** Legacy flat gallery kept so existing seed `GALLERY[n]` references still typecheck. */
const GALLERY = [
  ...MEDIA.statue,
  ...MEDIA.hoodie,
  ...MEDIA.deskmat,
  ...MEDIA.controller,
  ...MEDIA.tee,
  ...MEDIA.keycap,
  ...MEDIA.hat,
  ...MEDIA.poster,
  ...MEDIA.console,
  ...MEDIA.collectible,
  ...MEDIA.jersey,
  ...MEDIA.mug,
  ...MEDIA.stand,
  ...MEDIA.default,
] as const;

type ProductSeed = Omit<Product, 'compareAtPrice' | 'imageUrls' | 'specifications' | 'additionalDetails' | 'brand'> & {
  brand?: string;
  compareAtPrice?: number;
  specifications?: Record<string, string>;
  additionalDetails?: string;
};

const CATEGORY_SPECS: Record<
  ProductCategory,
  { material: string; weight: string; care: string; pack: string }
> = {
  apparel: {
    material: 'Heavyweight cotton / fleece blend',
    weight: '480 g',
    care: 'Cold wash, hang dry',
    pack: 'Folded in branded poly mailer with size card',
  },
  'desk-gear': {
    material: 'Forge-grade polymer / aluminum',
    weight: '420–980 g',
    care: 'Wipe with dry microfiber',
    pack: 'Foam-lined carton with cable / mount kit',
  },
  collectibles: {
    material: 'Hand-finished resin / archival paper',
    weight: '0.4–1.8 kg',
    care: 'Keep out of direct sun',
    pack: 'Rigid foam cradle + authenticity sleeve',
  },
  'limited-drops': {
    material: 'Drop-specific forge finish',
    weight: '350–1.2 kg',
    care: 'Store sealed until first use',
    pack: 'Numbered outer sleeve + drop insert',
  },
};

/** Maps game IP lines to recognizable merch / publisher brands. */
const FRANCHISE_BRANDS: Record<string, string> = {
  'God of War Ragnarok': 'PlayStation',
  'God of War': 'PlayStation',
  'God of War III': 'PlayStation',
  'The Last of Us': 'PlayStation',
  'Black Myth: Wukong': 'Game Science',
  "Marvel's Spider-Man 2": 'Marvel Games',
  'Ghost of Tsushima': 'PlayStation',
  'Call of Duty': 'Activision',
  'Mythic Realms': 'Niðavellir Collectibles',
  'Pixel Circuit': 'Razer',
  'Nidavellir Forge': 'Niðavellir',
  'Arena Masters': 'HyperX',
  'Void League': 'Logitech G',
  'Neon Harbor': 'Corsair',
  'Solo Leveling': 'Crunchyroll',
  'Attack on Titan': 'MAPPA',
  'Demon Slayer': 'Aniplex',
  'Jujutsu Kaisen': 'MAPPA',
  Naruto: 'Viz Media',
  'One Piece': 'Toei Animation',
  'Dragon Ball': 'Bandai',
  'Spy x Family': 'Crunchyroll',
  'Chainsaw Man': 'MAPPA',
  'My Hero Academia': 'Funimation',
  'Death Note': 'Viz Media',
};

const FRANCHISE_PUBLISHERS: Record<string, string> = {
  'God of War Ragnarok': 'Sony Interactive Entertainment',
  'God of War': 'Sony Interactive Entertainment',
  'God of War III': 'Sony Interactive Entertainment',
  'The Last of Us': 'Sony Interactive Entertainment',
  'Black Myth: Wukong': 'Game Science',
  "Marvel's Spider-Man 2": 'Sony Interactive Entertainment',
  'Ghost of Tsushima': 'Sony Interactive Entertainment',
  'Call of Duty': 'Activision Blizzard',
  'Solo Leveling': 'A-1 Pictures',
  'Attack on Titan': 'MAPPA',
  'Demon Slayer': 'ufotable',
  'Jujutsu Kaisen': 'MAPPA',
  Naruto: 'Studio Pierrot',
  'One Piece': 'Toei Animation',
  'Dragon Ball': 'Toei Animation',
  'Spy x Family': 'WIT Studio',
  'Chainsaw Man': 'MAPPA',
  'My Hero Academia': 'Bones',
  'Death Note': 'Madhouse',
};

const ANIME_FRANCHISES = new Set(Object.keys(FRANCHISE_PUBLISHERS).filter((key) =>
  [
    'Solo Leveling',
    'Attack on Titan',
    'Demon Slayer',
    'Jujutsu Kaisen',
    'Naruto',
    'One Piece',
    'Dragon Ball',
    'Spy x Family',
    'Chainsaw Man',
    'My Hero Academia',
    'Death Note',
  ].includes(key),
));

function resolveBrand(seed: ProductSeed): string {
  return seed.brand ?? FRANCHISE_BRANDS[seed.franchise] ?? 'Niðavellir';
}

function hashId(id: string): number {
  let hash = 0;
  for (let i = 0; i < id.length; i += 1) {
    hash = (hash * 31 + id.charCodeAt(i)) >>> 0;
  }
  return hash;
}

function inferMediaKind(seed: ProductSeed): MediaKind {
  const blob = `${seed.name} ${seed.tags.join(' ')} ${seed.category}`.toLowerCase();
  if (blob.includes('hoodie') || blob.includes('crewneck')) return 'hoodie';
  if (blob.includes('jersey')) return 'jersey';
  if (blob.includes('tee') || blob.includes('t-shirt') || /\bshirt\b/.test(blob)) return 'tee';
  if (blob.includes('poster') || blob.includes('print')) return 'poster';
  if (blob.includes('deskmat') || blob.includes('mousepad')) return 'deskmat';
  if (blob.includes('controller') || blob.includes('joy-con') || blob.includes('dualsense') || blob.includes('grip')) {
    return 'controller';
  }
  if (
    blob.includes('console') ||
    blob.includes('ps5') ||
    blob.includes('xbox') ||
    blob.includes('nintendo') ||
    blob.includes('switch')
  ) {
    return 'console';
  }
  if (blob.includes('statue') || blob.includes('bust') || blob.includes('figurine') || blob.includes('guardian')) {
    return 'statue';
  }
  if (blob.includes('mug') || blob.includes('cup') || blob.includes('coaster')) return 'mug';
  if (blob.includes('cap') || blob.includes('beanie') || blob.includes('hat')) return 'hat';
  if (blob.includes('keycap') || blob.includes('keyboard')) return 'keycap';
  if (blob.includes('cable')) return 'cable';
  if (blob.includes('light') || blob.includes('monitor light')) return 'light';
  if (blob.includes('jacket')) return 'jacket';
  if (blob.includes('tote') || blob.includes('bag')) return 'bag';
  if (blob.includes('notebook')) return 'notebook';
  if (blob.includes('stand') || blob.includes('dock') || blob.includes('wrist') || blob.includes('organizer')) {
    return 'stand';
  }
  if (
    blob.includes('pin') ||
    blob.includes('coin') ||
    blob.includes('plaque') ||
    blob.includes('keychain') ||
    blob.includes('blade')
  ) {
    return 'collectible';
  }
  if (seed.category === 'apparel') return 'tee';
  if (seed.category === 'desk-gear') return 'deskmat';
  if (seed.category === 'collectibles') return 'collectible';
  return 'default';
}

function resolveProductImages(seed: ProductSeed): { imageUrl: string; imageUrls: string[] } {
  const kind = inferMediaKind(seed);
  const pool = MEDIA[kind];
  const start = hashId(seed.id) % pool.length;
  const imageUrls = Array.from({ length: Math.min(4, pool.length) }, (_, i) => pool[(start + i) % pool.length]!);
  return { imageUrl: imageUrls[0]!, imageUrls };
}

function completeProduct(seed: ProductSeed): Product {
  const cat = CATEGORY_SPECS[seed.category];
  const media = resolveProductImages(seed);
  const compareAtPrice = seed.compareAtPrice ?? Math.round(seed.price * 1.28);
  const brand = resolveBrand(seed);
  const publisher = FRANCHISE_PUBLISHERS[seed.franchise];

  const extraTags: string[] = [];
  if (seed.category === 'apparel') extraTags.push('fashion');
  if (seed.category === 'desk-gear') extraTags.push('computer-it');
  const blob = `${seed.name} ${seed.tags.join(' ')}`.toLowerCase();
  if (blob.includes('controller')) extraTags.push('controller', 'console');
  if (blob.includes('console') || blob.includes('ps5') || blob.includes('xbox') || blob.includes('nintendo')) {
    extraTags.push('console');
  }
  if (blob.includes('ps5') || blob.includes('playstation')) extraTags.push('ps5');
  if (blob.includes('xbox')) extraTags.push('xbox');
  if (blob.includes('nintendo') || blob.includes('switch')) extraTags.push('nintendo');
  if (blob.includes('tee') || blob.includes('t-shirt')) extraTags.push('tee');
  if (blob.includes('hoodie')) extraTags.push('hoodie');
  if (blob.includes('jersey')) extraTags.push('jersey');
  if (blob.includes('poster')) extraTags.push('poster');
  if (ANIME_FRANCHISES.has(seed.franchise)) extraTags.push('anime');

  return {
    ...seed,
    brand,
    imageUrl: media.imageUrl,
    imageUrls: media.imageUrls,
    tags: [...new Set([...seed.tags, ...extraTags])],
    compareAtPrice,
    specifications: {
      SKU: seed.id.replace('prod-', 'NDV-').toUpperCase(),
      Brand: brand,
      Franchise: seed.franchise,
      ...(publisher ? { Publisher: publisher } : {}),
      Category: seed.category.replace(/-/g, ' '),
      Material: cat.material,
      Origin: 'Niðavellir Studio',
      Weight: cat.weight,
      Care: cat.care,
      ...seed.specifications,
    },
    additionalDetails:
      seed.additionalDetails ??
      `${cat.pack}. Colour may shift slightly under stage lighting. Size swaps and spare parts are handled through support within the return window.`,
  };
}

/** Catalog tag used by Home “You may also like” and the also-like PLP. */
export const ALSO_LIKE_TAG = 'you-may-also-like';

const seeds: ProductSeed[] = [
  // —— Collectibles ——
  {
    id: 'prod-odin-statue',
    name: 'Odin Desk Guardian',
    category: 'collectibles',
    franchise: 'Mythic Realms',
    description: 'Hand-painted resin statue with numbered authenticity card and stone-look base.',
    price: 4499,
    compareAtPrice: 5999,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 312,
    stock: 18,
    tags: ['Collector Grade', 'Numbered', 'statue', ALSO_LIKE_TAG],
    imageUrl: GALLERY[0],
    isLimitedDrop: true,
    specifications: { Edition: '01 / 500', Height: '22 cm' },
  },
  {
    id: 'prod-signed-print',
    name: 'Grand Finals Print',
    category: 'collectibles',
    franchise: 'Mythic Realms',
    description: 'Numbered archival print from championship stage night — giclée on cotton rag.',
    price: 1599,
    compareAtPrice: 2199,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 64,
    stock: 12,
    tags: ['Print', 'Numbered', 'art', ALSO_LIKE_TAG],
    imageUrl: GALLERY[7],
    isLimitedDrop: true,
    specifications: { Size: 'A3', Paper: 'Archival cotton rag' },
  },
  {
    id: 'prod-valkyrie-bust',
    name: 'Valkyrie Mini Bust',
    category: 'collectibles',
    franchise: 'Mythic Realms',
    description: 'Compact painted bust with brushed-steel stand — desk-scale mythology.',
    price: 2899,
    compareAtPrice: 3499,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 128,
    stock: 22,
    tags: ['Collector Grade', 'bust', 'statue'],
    imageUrl: GALLERY[10],
    isLimitedDrop: false,
    specifications: { Height: '14 cm', Finish: 'Matte enamel' },
  },
  {
    id: 'prod-forge-coin',
    name: 'Anvil Challenge Coin',
    category: 'collectibles',
    franchise: 'Nidavellir Forge',
    description: 'Dual-sided enamel challenge coin in a clear display case.',
    price: 699,
    compareAtPrice: 999,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 203,
    stock: 80,
    tags: ['Coin', 'Enamel', 'gift', ALSO_LIKE_TAG],
    imageUrl: GALLERY[14],
    isLimitedDrop: false,
    specifications: { Diameter: '40 mm', Case: 'Acrylic' },
  },
  {
    id: 'prod-lan-plaque',
    name: 'LAN Night Plaque',
    category: 'collectibles',
    franchise: 'Arena Masters',
    description: 'Brushed aluminum plaque with laser-etched roster grid — shelf or wall mount.',
    price: 1899,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 41,
    stock: 15,
    tags: ['Plaque', 'Metal', 'LAN'],
    imageUrl: GALLERY[11],
    isLimitedDrop: false,
    specifications: { Size: '20 × 15 cm', Mount: 'Wall / desk' },
  },

  // —— Apparel ——
  {
    id: 'prod-arcade-hoodie',
    name: 'Arcade Night Hoodie',
    category: 'apparel',
    franchise: 'Pixel Circuit',
    description: 'Heavyweight fleece hoodie with embroidered sleeve patch and kangaroo pocket.',
    price: 2499,
    compareAtPrice: 3299,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 184,
    stock: 42,
    tags: ['Oversized', 'Embroidered', 'hoodie', ALSO_LIKE_TAG],
    imageUrl: GALLERY[1],
    isLimitedDrop: false,
    specifications: { Fit: 'Relaxed', GSM: '380' },
  },
  {
    id: 'prod-pro-jersey',
    name: 'Stage Black Pro Jersey',
    category: 'apparel',
    franchise: 'Arena Masters',
    description: 'Match-day jersey with sublimated lineup marks, mesh side panels, and pro collar.',
    price: 2799,
    compareAtPrice: 3499,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 221,
    stock: 36,
    tags: ['Jersey', 'Pro Kit', ALSO_LIKE_TAG],
    imageUrl: GALLERY[4],
    isLimitedDrop: false,
    specifications: { Fit: 'Athletic', Panels: 'Mesh sides' },
  },
  {
    id: 'prod-team-cap',
    name: 'Circuit Night Cap',
    category: 'apparel',
    franchise: 'Pixel Circuit',
    description: 'Structured cap with tonal mark — built for LAN weekends and travel days.',
    price: 999,
    compareAtPrice: 1299,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 88,
    stock: 54,
    tags: ['Cap', 'Street', 'hat'],
    imageUrl: GALLERY[6],
    isLimitedDrop: false,
    specifications: { Closure: 'Snapback', Brim: 'Curved' },
  },
  {
    id: 'prod-void-hoodie',
    name: 'Void League Zip Hoodie',
    category: 'apparel',
    franchise: 'Void League',
    description: 'Full-zip tech hoodie with reflective mark and brushed interior.',
    price: 2699,
    compareAtPrice: 3199,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 97,
    stock: 31,
    tags: ['hoodie', 'Zip', 'Reflective', ALSO_LIKE_TAG],
    imageUrl: GALLERY[15],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', Closure: 'Full zip' },
  },
  {
    id: 'prod-forge-crew',
    name: 'Forge Mark Crewneck',
    category: 'apparel',
    franchise: 'Nidavellir Forge',
    description: 'Midweight crew with tonal anvil embroidery on chest and cuff rib.',
    price: 1999,
    compareAtPrice: 2499,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 156,
    stock: 48,
    tags: ['Crew', 'Embroidered', 'street'],
    imageUrl: GALLERY[9],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '320' },
  },
  {
    id: 'prod-arena-shorts',
    name: 'Arena Warmup Shorts',
    category: 'apparel',
    franchise: 'Arena Masters',
    description: 'Lightweight training shorts with zip pocket and sublimated side stripe.',
    price: 1299,
    compareAtPrice: 1699,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 73,
    stock: 60,
    tags: ['Shorts', 'Warmup', 'Pro Kit'],
    imageUrl: GALLERY[12],
    isLimitedDrop: false,
    specifications: { Inseam: '18 cm', Pocket: 'Secure zip' },
  },
  {
    id: 'prod-pixel-tee',
    name: 'Signal Grid Tee',
    category: 'apparel',
    franchise: 'Pixel Circuit',
    description: 'Soft heavyweight tee with front grid print and tonal neck tape.',
    price: 1199,
    compareAtPrice: 1499,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 210,
    stock: 72,
    tags: ['Tee', 'Print', 'street', ALSO_LIKE_TAG],
    imageUrl: GALLERY[9],
    isLimitedDrop: false,
    specifications: { Fit: 'Boxy', GSM: '240' },
  },
  {
    id: 'prod-neon-beanie',
    name: 'Neon Harbor Beanie',
    category: 'apparel',
    franchise: 'Neon Harbor',
    description: 'Rib-knit beanie with woven label — cold booths and late queues.',
    price: 799,
    compareAtPrice: 999,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 119,
    stock: 65,
    tags: ['Beanie', 'Knit', 'hat'],
    imageUrl: GALLERY[13],
    isLimitedDrop: false,
    specifications: { Knit: 'Double rib', Label: 'Woven' },
  },

  // —— Desk gear ——
  {
    id: 'prod-rgb-mat',
    name: 'Runestone RGB Deskmat',
    category: 'desk-gear',
    franchise: 'Nidavellir Forge',
    description: 'Extended stitched deskmat with low-profile RGB edge lighting and anti-slip base.',
    price: 3299,
    compareAtPrice: 4199,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 96,
    stock: 25,
    tags: ['RGB', 'XL', 'deskmat', ALSO_LIKE_TAG],
    imageUrl: GALLERY[2],
    isLimitedDrop: false,
    specifications: { Size: '900 × 400 mm', Edge: 'RGB stitched' },
  },
  {
    id: 'prod-keycap-set',
    name: 'Rune Legend Keycap Set',
    category: 'desk-gear',
    franchise: 'Nidavellir Forge',
    description: 'PBT keycaps with muted legends for a clean competitive desk.',
    price: 2199,
    compareAtPrice: 2799,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 143,
    stock: 28,
    tags: ['PBT', 'Keyboard', 'keycap', ALSO_LIKE_TAG],
    imageUrl: GALLERY[5],
    isLimitedDrop: false,
    specifications: { Profile: 'Cherry', Material: 'PBT doubleshot' },
  },
  {
    id: 'prod-headset-stand',
    name: 'Silent Forge Headset Dock',
    category: 'desk-gear',
    franchise: 'Nidavellir Forge',
    description: 'Weighted aluminum dock that keeps the headset line clean between matches.',
    price: 1799,
    compareAtPrice: 2299,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 109,
    stock: 21,
    tags: ['Aluminum', 'Setup', 'headset', ALSO_LIKE_TAG],
    imageUrl: GALLERY[8],
    isLimitedDrop: false,
    specifications: { Base: 'Weighted aluminum', Height: '28 cm' },
  },
  {
    id: 'prod-wrist-rest',
    name: 'Forge Line Wrist Rest',
    category: 'desk-gear',
    franchise: 'Nidavellir Forge',
    description: 'Memory-foam wrist rest with stitched cover matching Runestone mats.',
    price: 999,
    compareAtPrice: 1399,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 87,
    stock: 40,
    tags: ['Wrist', 'Setup', 'Keyboard'],
    imageUrl: GALLERY[2],
    isLimitedDrop: false,
    specifications: { Length: '360 mm', Fill: 'Memory foam' },
  },
  {
    id: 'prod-cable-kit',
    name: 'Clean Desk Cable Kit',
    category: 'desk-gear',
    franchise: 'Pixel Circuit',
    description: 'Braided USB-C / USB-A set with magnetic clips and under-desk anchors.',
    price: 1499,
    compareAtPrice: 1899,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 132,
    stock: 55,
    tags: ['Cable', 'Setup', 'USB-C'],
    imageUrl: GALLERY[15],
    isLimitedDrop: false,
    specifications: { Lengths: '1 m / 2 m', Finish: 'Braided black' },
  },
  {
    id: 'prod-mousepad-pro',
    name: 'Void Control Mousepad',
    category: 'desk-gear',
    franchise: 'Void League',
    description: 'Medium control pad with dense foam core — consistent glide for aim work.',
    price: 1299,
    compareAtPrice: 1699,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 268,
    stock: 44,
    tags: ['Mousepad', 'Control', 'deskmat', ALSO_LIKE_TAG],
    imageUrl: GALLERY[16],
    isLimitedDrop: false,
    specifications: { Size: '450 × 400 mm', Surface: 'Control weave' },
  },
  {
    id: 'prod-monitor-light',
    name: 'Harbor Bar Monitor Light',
    category: 'desk-gear',
    franchise: 'Neon Harbor',
    description: 'Screenbar light with asymmetric beam — no glare on glossy panels.',
    price: 3499,
    compareAtPrice: 4299,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 76,
    stock: 19,
    tags: ['Light', 'Setup', 'Monitor'],
    imageUrl: GALLERY[17],
    isLimitedDrop: false,
    specifications: { Clamp: '10–32 mm', CCT: '2700–6500 K' },
  },
  {
    id: 'prod-controller-grip',
    name: 'Arena Soft Controller Grips',
    category: 'desk-gear',
    franchise: 'Arena Masters',
    description: 'Textured silicone grips for dualsense-style controllers — sweat-ready.',
    price: 599,
    compareAtPrice: 899,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 154,
    stock: 90,
    tags: ['Controller', 'Grip', 'accessory'],
    imageUrl: GALLERY[3],
    isLimitedDrop: false,
    specifications: { Fit: 'Dualsense-style', Material: 'Silicone' },
  },

  // —— Limited drops ——
  {
    id: 'prod-controller-stand',
    name: 'Forged Controller Stand',
    category: 'limited-drops',
    franchise: 'Arena Masters',
    description: 'Metal display stand for controllers, headsets, and signed gear — Drop 02 run.',
    price: 1899,
    compareAtPrice: 2499,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 71,
    stock: 9,
    tags: ['Metal Build', 'Drop 02', 'controller', ALSO_LIKE_TAG],
    imageUrl: GALLERY[3],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 02', Finish: 'Brushed steel' },
  },
  {
    id: 'prod-drop-tee',
    name: 'Echo Line Tee',
    category: 'limited-drops',
    franchise: 'Arena Masters',
    description: 'Short-run heavyweight tee. One colorway, one window.',
    price: 1499,
    compareAtPrice: 1999,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 57,
    stock: 14,
    tags: ['Tee', 'Drop 03'],
    imageUrl: GALLERY[9],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 03', Colorway: 'Echo Black' },
  },
  {
    id: 'prod-mythic-blade',
    name: 'Mythic Edge Desk Blade',
    category: 'limited-drops',
    franchise: 'Mythic Realms',
    description: 'Letter-opener scale prop blade with etched runes and display sheath.',
    price: 3999,
    compareAtPrice: 4999,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 38,
    stock: 6,
    tags: ['Prop', 'Numbered', 'Drop 04', ALSO_LIKE_TAG],
    imageUrl: GALLERY[0],
    isLimitedDrop: true,
    specifications: { Edition: '01 / 250', Length: '28 cm' },
  },
  {
    id: 'prod-void-jacket',
    name: 'Void Night Coach Jacket',
    category: 'limited-drops',
    franchise: 'Void League',
    description: 'Water-resistant coach jacket with reflective mark — booth-to-street layer.',
    price: 4599,
    compareAtPrice: 5499,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 29,
    stock: 11,
    tags: ['Jacket', 'Drop 05', 'Reflective'],
    imageUrl: GALLERY[1],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 05', Shell: 'Water-resistant' },
  },
  {
    id: 'prod-pixel-cart',
    name: 'Circuit Cart Pin Set',
    category: 'limited-drops',
    franchise: 'Pixel Circuit',
    description: 'Five enamel pins on a numbered backing card — Drop 06 soft goods.',
    price: 899,
    compareAtPrice: 1299,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 112,
    stock: 0,
    tags: ['Pins', 'Enamel', 'Drop 06', 'gift'],
    imageUrl: GALLERY[14],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 06', Count: '5 pins' },
  },
  {
    id: 'prod-harbor-tote',
    name: 'Harbor Night Tote',
    category: 'limited-drops',
    franchise: 'Neon Harbor',
    description: 'Heavy canvas tote with interior laptop sleeve — Drop 07 travel piece.',
    price: 1799,
    compareAtPrice: 2299,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 48,
    stock: 17,
    tags: ['Tote', 'Drop 07', 'Travel'],
    imageUrl: GALLERY[13],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 07', Sleeve: '15″ laptop' },
  },
  {
    id: 'prod-forge-bundle',
    name: 'Desk Forge Starter Bundle',
    category: 'limited-drops',
    franchise: 'Nidavellir Forge',
    description: 'Matched deskmat + wrist rest + cable clips in one numbered sleeve.',
    price: 4999,
    compareAtPrice: 6499,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 33,
    stock: 8,
    tags: ['Bundle', 'Setup', 'deskmat', 'Drop 08', ALSO_LIKE_TAG],
    imageUrl: GALLERY[2],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 08', Includes: 'Mat + rest + clips' },
  },

  // —— Game franchise merch (shirts, desk, posters) ——
  // God of War
  {
    id: 'prod-gow-ragnarok-tee',
    name: 'Ragnarök Nine Realms Tee',
    category: 'apparel',
    franchise: 'God of War Ragnarok',
    description: 'Heavyweight tee with frost-bite palette and back print inspired by the nine realms journey.',
    price: 1499,
    compareAtPrice: 1999,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 342,
    stock: 55,
    tags: ['Tee', 'Shirt', 'god-of-war', 'ragnarok', ALSO_LIKE_TAG],
    imageUrl: GALLERY[29],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '260' },
  },
  {
    id: 'prod-gow-ragnarok-hoodie',
    name: 'Leviathan Frost Hoodie',
    category: 'apparel',
    franchise: 'God of War Ragnarok',
    description: 'Fleece hoodie with axe-strike chest mark and ice-blue drawcord — father-and-son run energy.',
    price: 3299,
    compareAtPrice: 4199,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 198,
    stock: 28,
    tags: ['Hoodie', 'Shirt', 'god-of-war', 'ragnarok', ALSO_LIKE_TAG],
    imageUrl: GALLERY[1],
    isLimitedDrop: false,
    specifications: { Fit: 'Relaxed', GSM: '400' },
  },
  {
    id: 'prod-gow-ragnarok-mat',
    name: 'Nine Realms XL Deskmat',
    category: 'desk-gear',
    franchise: 'God of War Ragnarok',
    description: 'Stitched edge deskmat with realm-map artwork — fits keyboard + mouse for long mythic sessions.',
    price: 2499,
    compareAtPrice: 3199,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 156,
    stock: 34,
    tags: ['Deskmat', 'desk', 'god-of-war', 'ragnarok', ALSO_LIKE_TAG],
    imageUrl: GALLERY[19],
    isLimitedDrop: false,
    specifications: { Size: '900 × 400 mm', Base: 'Anti-slip rubber' },
  },
  {
    id: 'prod-gow-ragnarok-poster',
    name: 'Ragnarök Key Art Poster',
    category: 'collectibles',
    franchise: 'God of War Ragnarok',
    description: 'Matte-finish A2 poster with realm journey artwork — ships in reinforced tube.',
    price: 899,
    compareAtPrice: 1299,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 267,
    stock: 62,
    tags: ['Poster', 'Print', 'god-of-war', 'ragnarok', ALSO_LIKE_TAG],
    imageUrl: GALLERY[28],
    isLimitedDrop: false,
    specifications: { Size: 'A2', Finish: 'Matte' },
  },
  {
    id: 'prod-gow-classic-tee',
    name: 'Spartan Omega Tee',
    category: 'apparel',
    franchise: 'God of War',
    description: 'Classic crimson-and-ash tee celebrating the original mythic saga — soft ring-spun cotton.',
    price: 1299,
    compareAtPrice: 1699,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 410,
    stock: 68,
    tags: ['Tee', 'Shirt', 'god-of-war', ALSO_LIKE_TAG],
    imageUrl: GALLERY[9],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '240' },
  },
  {
    id: 'prod-gow3-statue',
    name: 'Olympus Fall Mini Statue',
    category: 'collectibles',
    franchise: 'God of War III',
    description: 'Painted resin mini with temple-rubble base — tribute piece to the trilogy finale.',
    price: 3799,
    compareAtPrice: 4799,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 89,
    stock: 14,
    tags: ['Statue', 'Collectible', 'god-of-war', 'gow-3'],
    imageUrl: GALLERY[31],
    isLimitedDrop: true,
    specifications: { Height: '18 cm', Material: 'Hand-painted resin' },
  },
  {
    id: 'prod-gow-coaster-set',
    name: 'Leviathan Coaster Set',
    category: 'desk-gear',
    franchise: 'God of War',
    description: 'Four cork-backed coasters with rune-etched axe motifs — keeps the desk line clean.',
    price: 699,
    compareAtPrice: 999,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 124,
    stock: 75,
    tags: ['Coaster', 'desk', 'table', 'god-of-war'],
    imageUrl: GALLERY[18],
    isLimitedDrop: false,
    specifications: { Count: '4', Diameter: '90 mm' },
  },

  // The Last of Us
  {
    id: 'prod-tlou-firefly-tee',
    name: 'Firefly Emblem Survivor Tee',
    category: 'apparel',
    franchise: 'The Last of Us',
    description: 'Weathered-fit tee with glow-mark chest print — look for the light.',
    price: 1399,
    compareAtPrice: 1799,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 389,
    stock: 47,
    tags: ['Tee', 'Shirt', 'last-of-us', 'tlou', ALSO_LIKE_TAG],
    imageUrl: GALLERY[20],
    isLimitedDrop: false,
    specifications: { Fit: 'Relaxed', GSM: '250' },
  },
  {
    id: 'prod-tlou-hoodie',
    name: 'Outbreak Zone Hoodie',
    category: 'apparel',
    franchise: 'The Last of Us',
    description: 'Heavy fleece with muted green palette and cord-lock hood — built for long story nights.',
    price: 2999,
    compareAtPrice: 3799,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 176,
    stock: 33,
    tags: ['Hoodie', 'Shirt', 'last-of-us', 'tlou', ALSO_LIKE_TAG],
    imageUrl: GALLERY[1],
    isLimitedDrop: false,
    specifications: { Fit: 'Oversized', GSM: '390' },
  },
  {
    id: 'prod-tlou-poster',
    name: 'Look for the Light Poster',
    category: 'collectibles',
    franchise: 'The Last of Us',
    description: 'Moody A2 poster with overgrown-city silhouette — archival matte stock.',
    price: 849,
    compareAtPrice: 1199,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 298,
    stock: 58,
    tags: ['Poster', 'Print', 'last-of-us', 'tlou', ALSO_LIKE_TAG],
    imageUrl: GALLERY[33],
    isLimitedDrop: false,
    specifications: { Size: 'A2', Paper: 'Archival matte' },
  },
  {
    id: 'prod-tlou-desk-mat',
    name: 'Cordyceps Zone Deskmat',
    category: 'desk-gear',
    franchise: 'The Last of Us',
    description: 'Extended deskmat with spore-pattern edge stitch — control surface for survival runs.',
    price: 2199,
    compareAtPrice: 2799,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 143,
    stock: 39,
    tags: ['Deskmat', 'desk', 'table', 'last-of-us'],
    imageUrl: GALLERY[2],
    isLimitedDrop: false,
    specifications: { Size: '800 × 350 mm', Surface: 'Control weave' },
  },
  {
    id: 'prod-tlou-mug',
    name: 'Jackson Settlement Mug',
    category: 'desk-gear',
    franchise: 'The Last of Us',
    description: 'Ceramic mug with heat-reveal mark — desk companion for late episode marathons.',
    price: 599,
    compareAtPrice: 899,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 211,
    stock: 88,
    tags: ['Mug', 'desk', 'table', 'last-of-us', 'gift'],
    imageUrl: GALLERY[29],
    isLimitedDrop: false,
    specifications: { Capacity: '350 ml', Finish: 'Matte glaze' },
  },

  // Black Myth: Wukong
  {
    id: 'prod-wukong-journey-tee',
    name: 'Journey West Monkey King Tee',
    category: 'apparel',
    franchise: 'Black Myth: Wukong',
    description: 'Gold-foil chest mark on black heavyweight cotton — mythic action energy.',
    price: 1599,
    compareAtPrice: 2099,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 512,
    stock: 44,
    tags: ['Tee', 'Shirt', 'wukong', 'black-myth', ALSO_LIKE_TAG],
    imageUrl: GALLERY[30],
    isLimitedDrop: false,
    specifications: { Fit: 'Boxy', GSM: '280' },
  },
  {
    id: 'prod-wukong-statue',
    name: 'Golden Staff Guardian Statue',
    category: 'collectibles',
    franchise: 'Black Myth: Wukong',
    description: 'Hand-finished desk statue with staff detail and stone-texture base.',
    price: 4299,
    compareAtPrice: 5499,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 167,
    stock: 16,
    tags: ['Statue', 'Collectible', 'wukong', 'black-myth', ALSO_LIKE_TAG],
    imageUrl: GALLERY[31],
    isLimitedDrop: true,
    specifications: { Height: '20 cm', Finish: 'Antique gold' },
  },
  {
    id: 'prod-wukong-poster',
    name: 'Mythic Mountain Poster',
    category: 'collectibles',
    franchise: 'Black Myth: Wukong',
    description: 'Temple-mist A1 poster print — ships flat in rigid mailer.',
    price: 999,
    compareAtPrice: 1399,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 234,
    stock: 51,
    tags: ['Poster', 'Print', 'wukong', 'black-myth', ALSO_LIKE_TAG],
    imageUrl: GALLERY[30],
    isLimitedDrop: false,
    specifications: { Size: 'A1', Paper: 'Satin finish' },
  },
  {
    id: 'prod-wukong-desk-organizer',
    name: 'Staff Shrine Desk Organizer',
    category: 'desk-gear',
    franchise: 'Black Myth: Wukong',
    description: 'Bamboo-style organizer with pen slot, phone ledge, and incense tray recess.',
    price: 1899,
    compareAtPrice: 2499,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 98,
    stock: 27,
    tags: ['Organizer', 'desk', 'table', 'wukong', 'black-myth'],
    imageUrl: GALLERY[29],
    isLimitedDrop: false,
    specifications: { Material: 'ABS + wood veneer', Slots: 'Pen / phone / tray' },
  },

  // Marvel's Spider-Man 2
  {
    id: 'prod-spidey2-swing-tee',
    name: 'Web Swing City Tee',
    category: 'apparel',
    franchise: "Marvel's Spider-Man 2",
    description: 'Skyline-back print tee with red web accent stitching — NYC rooftop energy.',
    price: 1499,
    compareAtPrice: 1899,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 445,
    stock: 61,
    tags: ['Tee', 'Shirt', 'spiderman', 'spider-man-2', ALSO_LIKE_TAG],
    imageUrl: GALLERY[24],
    isLimitedDrop: false,
    specifications: { Fit: 'Athletic', GSM: '250' },
  },
  {
    id: 'prod-spidey2-miles-hoodie',
    name: 'Miles Velocity Hoodie',
    category: 'apparel',
    franchise: "Marvel's Spider-Man 2",
    description: 'Black/red color-block hoodie with reflective web piping — night-swing layer.',
    price: 3199,
    compareAtPrice: 3999,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 287,
    stock: 29,
    tags: ['Hoodie', 'Shirt', 'spiderman', 'miles-morales', ALSO_LIKE_TAG],
    imageUrl: GALLERY[1],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', Panels: 'Reflective piping' },
  },
  {
    id: 'prod-spidey2-mousepad',
    name: 'Web Pattern XL Mousepad',
    category: 'desk-gear',
    franchise: "Marvel's Spider-Man 2",
    description: 'Speed-surface XL pad with crimson web grid — smooth flicks for action titles.',
    price: 1799,
    compareAtPrice: 2299,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 198,
    stock: 42,
    tags: ['Mousepad', 'desk', 'table', 'spiderman', ALSO_LIKE_TAG],
    imageUrl: GALLERY[25],
    isLimitedDrop: false,
    specifications: { Size: '900 × 400 mm', Surface: 'Speed weave' },
  },
  {
    id: 'prod-spidey2-poster',
    name: 'Dual Spider Key Art Poster',
    category: 'collectibles',
    franchise: "Marvel's Spider-Man 2",
    description: 'City-night A2 poster celebrating the dual-hero skyline run.',
    price: 899,
    compareAtPrice: 1299,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 356,
    stock: 64,
    tags: ['Poster', 'Print', 'spiderman', 'spider-man-2', ALSO_LIKE_TAG],
    imageUrl: GALLERY[24],
    isLimitedDrop: false,
    specifications: { Size: 'A2', Finish: 'Gloss accent' },
  },

  // Ghost of Tsushima
  {
    id: 'prod-got-ronin-tee',
    name: 'Ghost Wind Ronin Tee',
    category: 'apparel',
    franchise: 'Ghost of Tsushima',
    description: 'Ink-wash front print on premium cotton — wind, steel, and sakura tones.',
    price: 1499,
    compareAtPrice: 1899,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 378,
    stock: 52,
    tags: ['Tee', 'Shirt', 'ghost-of-tsushima', 'got', ALSO_LIKE_TAG],
    imageUrl: GALLERY[22],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '260' },
  },
  {
    id: 'prod-got-deskmat',
    name: 'Sakura Storm Deskmat',
    category: 'desk-gear',
    franchise: 'Ghost of Tsushima',
    description: 'Wide deskmat with crimson-leaf border stitch — samurai desk setup essential.',
    price: 2399,
    compareAtPrice: 2999,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 167,
    stock: 36,
    tags: ['Deskmat', 'desk', 'table', 'ghost-of-tsushima', ALSO_LIKE_TAG],
    imageUrl: GALLERY[23],
    isLimitedDrop: false,
    specifications: { Size: '900 × 400 mm', Edge: 'Stitched crimson' },
  },
  {
    id: 'prod-got-poster',
    name: 'Tsushima Horizon Poster',
    category: 'collectibles',
    franchise: 'Ghost of Tsushima',
    description: 'Wide-format poster with torii-gate horizon line — matte museum stock.',
    price: 949,
    compareAtPrice: 1299,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 289,
    stock: 57,
    tags: ['Poster', 'Print', 'ghost-of-tsushima', ALSO_LIKE_TAG],
    imageUrl: GALLERY[23],
    isLimitedDrop: false,
    specifications: { Size: 'A2 wide', Paper: 'Museum matte' },
  },
  {
    id: 'prod-got-katana-stand',
    name: 'Katana Display Desk Stand',
    category: 'desk-gear',
    franchise: 'Ghost of Tsushima',
    description: 'Minimal wooden stand for replica blades, controllers, or headset — dojo desk piece.',
    price: 1699,
    compareAtPrice: 2199,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 112,
    stock: 24,
    tags: ['Stand', 'desk', 'table', 'ghost-of-tsushima', 'display'],
    imageUrl: GALLERY[21],
    isLimitedDrop: false,
    specifications: { Material: 'Walnut veneer', Width: '28 cm' },
  },

  // Call of Duty
  {
    id: 'prod-cod-ops-tee',
    name: 'Tactical Ops Field Tee',
    category: 'apparel',
    franchise: 'Call of Duty',
    description: 'Moisture-wick tee with squad patch print — ranked session ready.',
    price: 1299,
    compareAtPrice: 1699,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 523,
    stock: 82,
    tags: ['Tee', 'Shirt', 'call-of-duty', 'cod', ALSO_LIKE_TAG],
    imageUrl: GALLERY[26],
    isLimitedDrop: false,
    specifications: { Fit: 'Athletic', Fabric: 'Poly-cotton blend' },
  },
  {
    id: 'prod-cod-ghost-hoodie',
    name: 'Ghost Recon Hoodie',
    category: 'apparel',
    franchise: 'Call of Duty',
    description: 'Stealth-grey hoodie with skull-mark hood lining — loadout screen vibes.',
    price: 2899,
    compareAtPrice: 3599,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 312,
    stock: 38,
    tags: ['Hoodie', 'Shirt', 'call-of-duty', 'cod', 'ghost', ALSO_LIKE_TAG],
    imageUrl: GALLERY[1],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', Lining: 'Skull print' },
  },
  {
    id: 'prod-cod-rgb-mat',
    name: 'Warzone RGB Deskmat',
    category: 'desk-gear',
    franchise: 'Call of Duty',
    description: 'Tactical grid deskmat with RGB edge strip — squad comms desk setup.',
    price: 2799,
    compareAtPrice: 3499,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 189,
    stock: 31,
    tags: ['Deskmat', 'RGB', 'desk', 'call-of-duty', 'cod', ALSO_LIKE_TAG],
    imageUrl: GALLERY[2],
    isLimitedDrop: false,
    specifications: { Size: '900 × 400 mm', RGB: 'Edge strip' },
  },
  {
    id: 'prod-cod-poster',
    name: 'Task Force Key Art Poster',
    category: 'collectibles',
    franchise: 'Call of Duty',
    description: 'High-contrast A2 poster with squad silhouette — ships in reinforced tube.',
    price: 799,
    compareAtPrice: 1099,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 401,
    stock: 71,
    tags: ['Poster', 'Print', 'call-of-duty', 'cod', ALSO_LIKE_TAG],
    imageUrl: GALLERY[26],
    isLimitedDrop: false,
    specifications: { Size: 'A2', Finish: 'Matte' },
  },
  {
    id: 'prod-cod-pen-cup',
    name: 'Ammo Can Desk Cup',
    category: 'desk-gear',
    franchise: 'Call of Duty',
    description: 'Metal desk cup styled like a mini ammo crate — pens, markers, and loadout notes.',
    price: 899,
    compareAtPrice: 1199,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 156,
    stock: 66,
    tags: ['Cup', 'desk', 'table', 'call-of-duty', 'cod', 'gift'],
    imageUrl: GALLERY[33],
    isLimitedDrop: false,
    specifications: { Material: 'Steel', Capacity: '6 pens' },
  },
  {
    id: 'prod-cod-limited-jacket',
    name: 'Operator Drop Field Jacket',
    category: 'limited-drops',
    franchise: 'Call of Duty',
    description: 'Numbered-run field jacket with squad tab and MOLLE-inspired pocket grid.',
    price: 4999,
    compareAtPrice: 6499,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 67,
    stock: 9,
    tags: ['Jacket', 'call-of-duty', 'cod', 'Drop 09', ALSO_LIKE_TAG],
    imageUrl: GALLERY[26],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 09', Shell: 'Ripstop nylon' },
  },

  // Bonus cross-franchise desk + apparel
  {
    id: 'prod-gaming-poster-bundle',
    name: 'Legends Wall Poster Bundle',
    category: 'collectibles',
    franchise: 'Niðavellir Forge',
    description: 'Set of three A3 posters spanning myth, survival, and open-world epics — curated wall pack.',
    price: 1999,
    compareAtPrice: 2799,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 143,
    stock: 35,
    tags: ['Poster', 'Bundle', 'Print', 'gift', ALSO_LIKE_TAG],
    imageUrl: GALLERY[28],
    isLimitedDrop: false,
    specifications: { Count: '3 posters', Size: 'A3 each' },
  },
  {
    id: 'prod-pro-gamer-desk-set',
    name: 'Pro Gamer Desk Accessory Set',
    category: 'desk-gear',
    franchise: 'Niðavellir Forge',
    description: 'Coasters, cable clips, and phone stand in one matched desk kit for franchise fans.',
    price: 1499,
    compareAtPrice: 1999,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 178,
    stock: 48,
    tags: ['Bundle', 'desk', 'table', 'accessory', ALSO_LIKE_TAG],
    imageUrl: GALLERY[29],
    isLimitedDrop: false,
    specifications: { Includes: 'Coasters + clips + stand' },
  },
  {
    id: 'prod-dualsense-skin',
    name: 'Midnight DualSense Skin',
    category: 'desk-gear',
    franchise: 'Nidavellir Forge',
    description: 'Precision-cut controller skin for DualSense-style pads — grip without bulk.',
    price: 799,
    compareAtPrice: 1099,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 164,
    stock: 70,
    tags: ['Controller', 'console', 'skin'],
    imageUrl: GALLERY[3],
    isLimitedDrop: false,
    specifications: { Fit: 'DualSense-style', Finish: 'Matte vinyl' },
  },
  {
    id: 'prod-ps5-console-stand',
    name: 'Vertical Console Cradle',
    category: 'desk-gear',
    franchise: 'Nidavellir Forge',
    description: 'Weighted stand for current-gen consoles with cable channel and anti-tip foot.',
    price: 2299,
    compareAtPrice: 2899,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 91,
    stock: 22,
    tags: ['console', 'PS5', 'stand', ALSO_LIKE_TAG],
    imageUrl: GALLERY[20],
    isLimitedDrop: false,
    specifications: { Fit: 'Current-gen tower', Material: 'ABS + steel' },
  },
  {
    id: 'prod-ps5-dualsense-skin',
    name: 'PS5 DualSense Soft Skin',
    category: 'desk-gear',
    franchise: 'Nidavellir Forge',
    description: 'Anti-slip silicone skin for DualSense with raised trigger grips.',
    price: 899,
    compareAtPrice: 1299,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 214,
    stock: 64,
    tags: ['console', 'PS5', 'controller', 'skin', ALSO_LIKE_TAG],
    imageUrl: GALLERY[19],
    isLimitedDrop: false,
    specifications: { Fit: 'DualSense', Material: 'Silicone' },
  },
  {
    id: 'prod-xbox-series-tee',
    name: 'Xbox Series Forge Tee',
    category: 'apparel',
    franchise: 'Arena Masters',
    description: 'Black tee with green-accent controller mark — Xbox session fit.',
    price: 1199,
    compareAtPrice: 1599,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 178,
    stock: 55,
    tags: ['Tee', 'Shirt', 'console', 'xbox', ALSO_LIKE_TAG],
    imageUrl: GALLERY[10],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '240' },
  },
  {
    id: 'prod-xbox-series-pad',
    name: 'Xbox Series Control Deskmat',
    category: 'desk-gear',
    franchise: 'Arena Masters',
    description: 'Wide deskmat with Xbox Series silhouette grid — low-friction glide zone.',
    price: 2499,
    compareAtPrice: 3199,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 132,
    stock: 29,
    tags: ['Deskmat', 'console', 'xbox', 'desk', ALSO_LIKE_TAG],
    imageUrl: GALLERY[3],
    isLimitedDrop: false,
    specifications: { Size: '900 × 400 mm', Surface: 'Cloth' },
  },
  {
    id: 'prod-xbox-controller-case',
    name: 'Xbox Wireless Controller Case',
    category: 'desk-gear',
    franchise: 'Arena Masters',
    description: 'Hard-shell travel case for Xbox wireless controllers with foam insert.',
    price: 1499,
    compareAtPrice: 1999,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 97,
    stock: 41,
    tags: ['controller', 'console', 'xbox', 'case'],
    imageUrl: GALLERY[22],
    isLimitedDrop: false,
    specifications: { Fit: 'Xbox Wireless', Shell: 'ABS' },
  },
  {
    id: 'prod-nintendo-switch-tee',
    name: 'Nintendo Switch Dock Tee',
    category: 'apparel',
    franchise: 'Pixel Circuit',
    description: 'Soft tee with neon dock silhouette — couch co-op ready.',
    price: 1099,
    compareAtPrice: 1499,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 156,
    stock: 48,
    tags: ['Tee', 'Shirt', 'console', 'nintendo', 'switch', ALSO_LIKE_TAG],
    imageUrl: GALLERY[12],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '230' },
  },
  {
    id: 'prod-nintendo-switch-stand',
    name: 'Nintendo Switch Desk Dock Stand',
    category: 'desk-gear',
    franchise: 'Pixel Circuit',
    description: 'Angled acrylic stand for Switch in handheld or docked display mode.',
    price: 1299,
    compareAtPrice: 1699,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 88,
    stock: 37,
    tags: ['stand', 'console', 'nintendo', 'switch', 'desk'],
    imageUrl: GALLERY[21],
    isLimitedDrop: false,
    specifications: { Material: 'Acrylic', Angle: '22°' },
  },
  {
    id: 'prod-nintendo-joycon-grips',
    name: 'Nintendo Joy-Con Comfort Grips',
    category: 'desk-gear',
    franchise: 'Pixel Circuit',
    description: 'Soft-touch grips for Joy-Con pair — longer handheld sessions without fatigue.',
    price: 999,
    compareAtPrice: 1399,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 121,
    stock: 52,
    tags: ['controller', 'console', 'nintendo', 'switch', 'grip'],
    imageUrl: GALLERY[18],
    isLimitedDrop: false,
    specifications: { Fit: 'Joy-Con L/R', Material: 'TPE' },
  },

  // —— Anime merch ——
  {
    id: 'prod-solo-leveling-tee',
    name: 'Arise Shadow Monarch Tee',
    category: 'apparel',
    franchise: 'Solo Leveling',
    description: 'Heavyweight tee with monarch crest print — hunter-rank street fit.',
    price: 1399,
    compareAtPrice: 1799,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 276,
    stock: 48,
    tags: ['Tee', 'Shirt', 'anime', 'solo-leveling', ALSO_LIKE_TAG],
    imageUrl: GALLERY[9],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '250' },
  },
  {
    id: 'prod-solo-leveling-poster',
    name: 'Jinwoo Gate Poster',
    category: 'collectibles',
    franchise: 'Solo Leveling',
    description: 'A2 matte poster of the dungeon-gate skyline. Ships in a rigid tube.',
    price: 849,
    compareAtPrice: 1199,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 188,
    stock: 0,
    tags: ['Poster', 'Print', 'anime', 'solo-leveling', 'restocking'],
    imageUrl: GALLERY[28],
    isLimitedDrop: false,
    specifications: { Size: 'A2', Finish: 'Matte' },
  },
  {
    id: 'prod-aot-tee',
    name: 'Wings of Freedom Tee',
    category: 'apparel',
    franchise: 'Attack on Titan',
    description: 'Survey corps mark on black cotton — parade-ready street layer.',
    price: 1299,
    compareAtPrice: 1699,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 412,
    stock: 54,
    tags: ['Tee', 'Shirt', 'anime', 'aot', ALSO_LIKE_TAG],
    imageUrl: GALLERY[30],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '240' },
  },
  {
    id: 'prod-aot-keychain',
    name: 'ODM Gear Keychain',
    category: 'desk-gear',
    franchise: 'Attack on Titan',
    description: 'Metal ODM-inspired keychain for bags and desk hooks.',
    price: 499,
    compareAtPrice: 799,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 203,
    stock: 90,
    tags: ['Keychain', 'anime', 'aot', 'gift'],
    imageUrl: GALLERY[18],
    isLimitedDrop: false,
    specifications: { Material: 'Zinc alloy', Length: '6 cm' },
  },
  {
    id: 'prod-ds-hoodie',
    name: 'Breathing Forms Hoodie',
    category: 'apparel',
    franchise: 'Demon Slayer',
    description: 'Fleece hoodie with haori-stripe cuffs — night-hashira energy.',
    price: 2899,
    compareAtPrice: 3599,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 331,
    stock: 36,
    tags: ['Hoodie', 'Shirt', 'anime', 'demon-slayer', ALSO_LIKE_TAG],
    imageUrl: GALLERY[1],
    isLimitedDrop: false,
    specifications: { Fit: 'Relaxed', GSM: '380' },
  },
  {
    id: 'prod-ds-poster',
    name: 'Hashira Lineup Poster',
    category: 'collectibles',
    franchise: 'Demon Slayer',
    description: 'Wide A2 print of the corps lineup. Archival inks on matte stock.',
    price: 899,
    compareAtPrice: 1299,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 298,
    stock: 41,
    tags: ['Poster', 'Print', 'anime', 'demon-slayer', ALSO_LIKE_TAG],
    imageUrl: GALLERY[23],
    isLimitedDrop: false,
    specifications: { Size: 'A2', Paper: 'Archival matte' },
  },
  {
    id: 'prod-jjk-tee',
    name: 'Cursed Energy Tee',
    category: 'apparel',
    franchise: 'Jujutsu Kaisen',
    description: 'Tokyo Jujutsu High mark on boxy heavyweight cotton.',
    price: 1399,
    compareAtPrice: 1799,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 367,
    stock: 52,
    tags: ['Tee', 'Shirt', 'anime', 'jujutsu-kaisen', ALSO_LIKE_TAG],
    imageUrl: GALLERY[15],
    isLimitedDrop: false,
    specifications: { Fit: 'Boxy', GSM: '260' },
  },
  {
    id: 'prod-jjk-figure',
    name: 'Domain Mini Acrylic',
    category: 'collectibles',
    franchise: 'Jujutsu Kaisen',
    description: 'Desk acrylic standee with domain-circle print and wood base.',
    price: 1199,
    compareAtPrice: 1599,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 142,
    stock: 0,
    tags: ['Acrylic', 'anime', 'jujutsu-kaisen', 'restocking'],
    imageUrl: GALLERY[31],
    isLimitedDrop: false,
    specifications: { Height: '15 cm', Base: 'Beech' },
  },
  {
    id: 'prod-naruto-tee',
    name: 'Hidden Leaf Crest Tee',
    category: 'apparel',
    franchise: 'Naruto',
    description: 'Village crest chest print on midweight cotton — academy-to-street.',
    price: 1199,
    compareAtPrice: 1499,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 488,
    stock: 71,
    tags: ['Tee', 'Shirt', 'anime', 'naruto', ALSO_LIKE_TAG],
    imageUrl: GALLERY[9],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '230' },
  },
  {
    id: 'prod-naruto-headband',
    name: 'Leaf Village Headband',
    category: 'apparel',
    franchise: 'Naruto',
    description: 'Metal-plate replica headband with adjustable cloth wrap.',
    price: 699,
    compareAtPrice: 999,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 256,
    stock: 80,
    tags: ['Headband', 'anime', 'naruto', 'gift'],
    imageUrl: GALLERY[6],
    isLimitedDrop: false,
    specifications: { Plate: 'Steel', Wrap: 'Cotton' },
  },
  {
    id: 'prod-onepiece-hoodie',
    name: 'Straw Hat Crew Hoodie',
    category: 'apparel',
    franchise: 'One Piece',
    description: 'Oversized hoodie with jolly-roger back print — grand line weekends.',
    price: 2699,
    compareAtPrice: 3399,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 401,
    stock: 39,
    tags: ['Hoodie', 'Shirt', 'anime', 'one-piece', ALSO_LIKE_TAG],
    imageUrl: GALLERY[1],
    isLimitedDrop: false,
    specifications: { Fit: 'Oversized', GSM: '370' },
  },
  {
    id: 'prod-onepiece-poster',
    name: 'Thousand Sunny Poster',
    category: 'collectibles',
    franchise: 'One Piece',
    description: 'Sea-horizon A2 poster of the crew ship. Tube packed.',
    price: 799,
    compareAtPrice: 1099,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 219,
    stock: 58,
    tags: ['Poster', 'Print', 'anime', 'one-piece'],
    imageUrl: GALLERY[33],
    isLimitedDrop: false,
    specifications: { Size: 'A2', Finish: 'Satin' },
  },
  {
    id: 'prod-dbz-tee',
    name: 'Saiyan Training Tee',
    category: 'apparel',
    franchise: 'Dragon Ball',
    description: 'Orange gi-inspired tee with kanji chest mark — capsule-corp wash.',
    price: 1299,
    compareAtPrice: 1699,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 522,
    stock: 66,
    tags: ['Tee', 'Shirt', 'anime', 'dragon-ball', ALSO_LIKE_TAG],
    imageUrl: GALLERY[4],
    isLimitedDrop: false,
    specifications: { Fit: 'Athletic', GSM: '240' },
  },
  {
    id: 'prod-dbz-mug',
    name: 'Capsule Corp Desk Mug',
    category: 'desk-gear',
    franchise: 'Dragon Ball',
    description: 'Ceramic mug with capsule logo — ranked session fuel.',
    price: 599,
    compareAtPrice: 899,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 174,
    stock: 84,
    tags: ['Mug', 'desk', 'anime', 'dragon-ball', 'gift'],
    imageUrl: GALLERY[29],
    isLimitedDrop: false,
    specifications: { Capacity: '350 ml', Finish: 'Gloss' },
  },
  {
    id: 'prod-spy-tee',
    name: 'For the Mission Tee',
    category: 'apparel',
    franchise: 'Spy x Family',
    description: 'Clean city-night print tee — family cover-story energy.',
    price: 1299,
    compareAtPrice: 1599,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 198,
    stock: 45,
    tags: ['Tee', 'Shirt', 'anime', 'spy-x-family', ALSO_LIKE_TAG],
    imageUrl: GALLERY[24],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '240' },
  },
  {
    id: 'prod-spy-pin',
    name: 'Anya Badge Pin Set',
    category: 'collectibles',
    franchise: 'Spy x Family',
    description: 'Three enamel pins on a backing card — desk, bag, or jacket.',
    price: 699,
    compareAtPrice: 999,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 156,
    stock: 0,
    tags: ['Pins', 'anime', 'spy-x-family', 'gift', 'restocking'],
    imageUrl: GALLERY[14],
    isLimitedDrop: true,
    specifications: { Count: '3 pins', Finish: 'Hard enamel' },
  },
  {
    id: 'prod-csm-hoodie',
    name: 'Devil Hunter Zip Hoodie',
    category: 'apparel',
    franchise: 'Chainsaw Man',
    description: 'Black zip hoodie with saw-mark sleeve print — public safety night layer.',
    price: 2999,
    compareAtPrice: 3799,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 211,
    stock: 27,
    tags: ['Hoodie', 'Shirt', 'anime', 'chainsaw-man', ALSO_LIKE_TAG],
    imageUrl: GALLERY[15],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', Closure: 'Full zip' },
  },
  {
    id: 'prod-csm-poster',
    name: 'Denji City Poster',
    category: 'collectibles',
    franchise: 'Chainsaw Man',
    description: 'Neon-street A2 poster. High-contrast print on matte stock.',
    price: 849,
    compareAtPrice: 1199,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 133,
    stock: 40,
    tags: ['Poster', 'Print', 'anime', 'chainsaw-man'],
    imageUrl: GALLERY[25],
    isLimitedDrop: false,
    specifications: { Size: 'A2', Finish: 'Matte' },
  },
  {
    id: 'prod-mha-tee',
    name: 'Plus Ultra Campus Tee',
    category: 'apparel',
    franchise: 'My Hero Academia',
    description: 'UA-inspired athletic tee with hero-course numbering.',
    price: 1299,
    compareAtPrice: 1699,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 344,
    stock: 59,
    tags: ['Tee', 'Shirt', 'anime', 'my-hero-academia', ALSO_LIKE_TAG],
    imageUrl: GALLERY[4],
    isLimitedDrop: false,
    specifications: { Fit: 'Athletic', GSM: '240' },
  },
  {
    id: 'prod-mha-deskmat',
    name: 'Hero Course Deskmat',
    category: 'desk-gear',
    franchise: 'My Hero Academia',
    description: 'Extended stitched mat with campus-grid artwork for study and ranked play.',
    price: 1999,
    compareAtPrice: 2599,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 121,
    stock: 33,
    tags: ['Deskmat', 'desk', 'anime', 'my-hero-academia'],
    imageUrl: GALLERY[2],
    isLimitedDrop: false,
    specifications: { Size: '800 × 350 mm', Edge: 'Stitched' },
  },
  {
    id: 'prod-deathnote-tee',
    name: 'Kira Rules Tee',
    category: 'apparel',
    franchise: 'Death Note',
    description: 'Minimal black tee with notebook-rule typography on the back.',
    price: 1299,
    compareAtPrice: 1699,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 267,
    stock: 44,
    tags: ['Tee', 'Shirt', 'anime', 'death-note', ALSO_LIKE_TAG],
    imageUrl: GALLERY[15],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '250' },
  },
  {
    id: 'prod-deathnote-notebook',
    name: 'Shinigami Desk Notebook',
    category: 'desk-gear',
    franchise: 'Death Note',
    description: 'Hardcover lined notebook with apple-mark bookmark — desk study piece.',
    price: 899,
    compareAtPrice: 1199,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 189,
    stock: 51,
    tags: ['Notebook', 'desk', 'anime', 'death-note', 'gift'],
    imageUrl: GALLERY[27],
    isLimitedDrop: false,
    specifications: { Pages: '192', Size: 'A5' },
  },
];

export const demoProducts: Product[] = seeds.map((seed) => completeProduct(seed));

export const demoMarketplaceOverview: MarketplaceOverview = {
  products: demoProducts,
  featuredProductId: 'prod-odin-statue',
  cart: [
    { productId: 'prod-odin-statue', quantity: 1 },
    { productId: 'prod-rgb-mat', quantity: 1 },
  ],
  latestOrder: {
    id: 'ORD-NDV-1048',
    status: 'packed',
    total: 7798,
    currency: 'INR',
    estimatedDelivery: '2026-08-12',
    itemCount: 2,
  },
};
