import type { MarketplaceOverview, Product, ProductCategory } from './types/index.js';

const GALLERY = [
  'https://images.unsplash.com/photo-1608889175123-8ee362201f81?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1605901309584-818e25960a8f?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1599669454699-248893617614?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1616587894289-86480e533129?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1486572788966-cfd3df93f05d?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=900&q=80',
] as const;

type ProductSeed = Omit<Product, 'compareAtPrice' | 'imageUrls' | 'specifications' | 'additionalDetails'> & {
  compareAtPrice?: number;
  specifications?: Record<string, string>;
  additionalDetails?: string;
};

const CATEGORY_SPECS: Record<
  ProductCategory,
  { material: string; weight: string; care: string; pack: string }
> = {
  apparel: {
    material: 'Heavyweight cotton / fleece blend',
    weight: '480 g',
    care: 'Cold wash, hang dry',
    pack: 'Folded in branded poly mailer with size card',
  },
  'desk-gear': {
    material: 'Forge-grade polymer / aluminum',
    weight: '420–980 g',
    care: 'Wipe with dry microfiber',
    pack: 'Foam-lined carton with cable / mount kit',
  },
  collectibles: {
    material: 'Hand-finished resin / archival paper',
    weight: '0.4–1.8 kg',
    care: 'Keep out of direct sun',
    pack: 'Rigid foam cradle + authenticity sleeve',
  },
  'limited-drops': {
    material: 'Drop-specific forge finish',
    weight: '350–1.2 kg',
    care: 'Store sealed until first use',
    pack: 'Numbered outer sleeve + drop insert',
  },
};

function completeProduct(seed: ProductSeed, extraImages: string[]): Product {
  const cat = CATEGORY_SPECS[seed.category];
  const imageUrls = [seed.imageUrl, ...extraImages.filter((url) => url !== seed.imageUrl)].slice(0, 4);
  const compareAtPrice = seed.compareAtPrice ?? Math.round(seed.price * 1.28);

  return {
    ...seed,
    imageUrls,
    compareAtPrice,
    specifications: {
      SKU: seed.id.replace('prod-', 'NDV-').toUpperCase(),
      Franchise: seed.franchise,
      Category: seed.category.replace(/-/g, ' '),
      Material: cat.material,
      Origin: 'Niðavellir Studio',
      Weight: cat.weight,
      Care: cat.care,
      ...seed.specifications,
    },
    additionalDetails:
      seed.additionalDetails ??
      `${cat.pack}. Colour may shift slightly under stage lighting. Size swaps and spare parts are handled through support within the return window.`,
  };
}

/** Catalog tag used by Home “You may also like” and the also-like PLP. */
export const ALSO_LIKE_TAG = 'you-may-also-like';

const seeds: ProductSeed[] = [
  // —— Collectibles ——
  {
    id: 'prod-odin-statue',
    name: 'Odin Desk Guardian',
    category: 'collectibles',
    franchise: 'Mythic Realms',
    description: 'Hand-painted resin statue with numbered authenticity card and stone-look base.',
    price: 4499,
    compareAtPrice: 5999,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 312,
    stock: 18,
    tags: ['Collector Grade', 'Numbered', 'statue', ALSO_LIKE_TAG],
    imageUrl: GALLERY[0],
    isLimitedDrop: true,
    specifications: { Edition: '01 / 500', Height: '22 cm' },
  },
  {
    id: 'prod-signed-print',
    name: 'Grand Finals Print',
    category: 'collectibles',
    franchise: 'Mythic Realms',
    description: 'Numbered archival print from championship stage night — giclée on cotton rag.',
    price: 1599,
    compareAtPrice: 2199,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 64,
    stock: 12,
    tags: ['Print', 'Numbered', 'art', ALSO_LIKE_TAG],
    imageUrl: GALLERY[7],
    isLimitedDrop: true,
    specifications: { Size: 'A3', Paper: 'Archival cotton rag' },
  },
  {
    id: 'prod-valkyrie-bust',
    name: 'Valkyrie Mini Bust',
    category: 'collectibles',
    franchise: 'Mythic Realms',
    description: 'Compact painted bust with brushed-steel stand — desk-scale mythology.',
    price: 2899,
    compareAtPrice: 3499,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 128,
    stock: 22,
    tags: ['Collector Grade', 'bust', 'statue'],
    imageUrl: GALLERY[10],
    isLimitedDrop: false,
    specifications: { Height: '14 cm', Finish: 'Matte enamel' },
  },
  {
    id: 'prod-forge-coin',
    name: 'Anvil Challenge Coin',
    category: 'collectibles',
    franchise: 'Nidavellir Forge',
    description: 'Dual-sided enamel challenge coin in a clear display case.',
    price: 699,
    compareAtPrice: 999,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 203,
    stock: 80,
    tags: ['Coin', 'Enamel', 'gift', ALSO_LIKE_TAG],
    imageUrl: GALLERY[14],
    isLimitedDrop: false,
    specifications: { Diameter: '40 mm', Case: 'Acrylic' },
  },
  {
    id: 'prod-lan-plaque',
    name: 'LAN Night Plaque',
    category: 'collectibles',
    franchise: 'Arena Masters',
    description: 'Brushed aluminum plaque with laser-etched roster grid — shelf or wall mount.',
    price: 1899,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 41,
    stock: 15,
    tags: ['Plaque', 'Metal', 'LAN'],
    imageUrl: GALLERY[11],
    isLimitedDrop: false,
    specifications: { Size: '20 × 15 cm', Mount: 'Wall / desk' },
  },

  // —— Apparel ——
  {
    id: 'prod-arcade-hoodie',
    name: 'Arcade Night Hoodie',
    category: 'apparel',
    franchise: 'Pixel Circuit',
    description: 'Heavyweight fleece hoodie with embroidered sleeve patch and kangaroo pocket.',
    price: 2499,
    compareAtPrice: 3299,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 184,
    stock: 42,
    tags: ['Oversized', 'Embroidered', 'hoodie', ALSO_LIKE_TAG],
    imageUrl: GALLERY[1],
    isLimitedDrop: false,
    specifications: { Fit: 'Relaxed', GSM: '380' },
  },
  {
    id: 'prod-pro-jersey',
    name: 'Stage Black Pro Jersey',
    category: 'apparel',
    franchise: 'Arena Masters',
    description: 'Match-day jersey with sublimated lineup marks, mesh side panels, and pro collar.',
    price: 2799,
    compareAtPrice: 3499,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 221,
    stock: 36,
    tags: ['Jersey', 'Pro Kit', ALSO_LIKE_TAG],
    imageUrl: GALLERY[4],
    isLimitedDrop: false,
    specifications: { Fit: 'Athletic', Panels: 'Mesh sides' },
  },
  {
    id: 'prod-team-cap',
    name: 'Circuit Night Cap',
    category: 'apparel',
    franchise: 'Pixel Circuit',
    description: 'Structured cap with tonal mark — built for LAN weekends and travel days.',
    price: 999,
    compareAtPrice: 1299,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 88,
    stock: 54,
    tags: ['Cap', 'Street', 'hat'],
    imageUrl: GALLERY[6],
    isLimitedDrop: false,
    specifications: { Closure: 'Snapback', Brim: 'Curved' },
  },
  {
    id: 'prod-void-hoodie',
    name: 'Void League Zip Hoodie',
    category: 'apparel',
    franchise: 'Void League',
    description: 'Full-zip tech hoodie with reflective mark and brushed interior.',
    price: 2699,
    compareAtPrice: 3199,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 97,
    stock: 31,
    tags: ['hoodie', 'Zip', 'Reflective', ALSO_LIKE_TAG],
    imageUrl: GALLERY[15],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', Closure: 'Full zip' },
  },
  {
    id: 'prod-forge-crew',
    name: 'Forge Mark Crewneck',
    category: 'apparel',
    franchise: 'Nidavellir Forge',
    description: 'Midweight crew with tonal anvil embroidery on chest and cuff rib.',
    price: 1999,
    compareAtPrice: 2499,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 156,
    stock: 48,
    tags: ['Crew', 'Embroidered', 'street'],
    imageUrl: GALLERY[9],
    isLimitedDrop: false,
    specifications: { Fit: 'Regular', GSM: '320' },
  },
  {
    id: 'prod-arena-shorts',
    name: 'Arena Warmup Shorts',
    category: 'apparel',
    franchise: 'Arena Masters',
    description: 'Lightweight training shorts with zip pocket and sublimated side stripe.',
    price: 1299,
    compareAtPrice: 1699,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 73,
    stock: 60,
    tags: ['Shorts', 'Warmup', 'Pro Kit'],
    imageUrl: GALLERY[12],
    isLimitedDrop: false,
    specifications: { Inseam: '18 cm', Pocket: 'Secure zip' },
  },
  {
    id: 'prod-pixel-tee',
    name: 'Signal Grid Tee',
    category: 'apparel',
    franchise: 'Pixel Circuit',
    description: 'Soft heavyweight tee with front grid print and tonal neck tape.',
    price: 1199,
    compareAtPrice: 1499,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 210,
    stock: 72,
    tags: ['Tee', 'Print', 'street', ALSO_LIKE_TAG],
    imageUrl: GALLERY[9],
    isLimitedDrop: false,
    specifications: { Fit: 'Boxy', GSM: '240' },
  },
  {
    id: 'prod-neon-beanie',
    name: 'Neon Harbor Beanie',
    category: 'apparel',
    franchise: 'Neon Harbor',
    description: 'Rib-knit beanie with woven label — cold booths and late queues.',
    price: 799,
    compareAtPrice: 999,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 119,
    stock: 65,
    tags: ['Beanie', 'Knit', 'hat'],
    imageUrl: GALLERY[13],
    isLimitedDrop: false,
    specifications: { Knit: 'Double rib', Label: 'Woven' },
  },

  // —— Desk gear ——
  {
    id: 'prod-rgb-mat',
    name: 'Runestone RGB Deskmat',
    category: 'desk-gear',
    franchise: 'Nidavellir Forge',
    description: 'Extended stitched deskmat with low-profile RGB edge lighting and anti-slip base.',
    price: 3299,
    compareAtPrice: 4199,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 96,
    stock: 25,
    tags: ['RGB', 'XL', 'deskmat', ALSO_LIKE_TAG],
    imageUrl: GALLERY[2],
    isLimitedDrop: false,
    specifications: { Size: '900 × 400 mm', Edge: 'RGB stitched' },
  },
  {
    id: 'prod-keycap-set',
    name: 'Rune Legend Keycap Set',
    category: 'desk-gear',
    franchise: 'Nidavellir Forge',
    description: 'PBT keycaps with muted legends for a clean competitive desk.',
    price: 2199,
    compareAtPrice: 2799,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 143,
    stock: 28,
    tags: ['PBT', 'Keyboard', 'keycap', ALSO_LIKE_TAG],
    imageUrl: GALLERY[5],
    isLimitedDrop: false,
    specifications: { Profile: 'Cherry', Material: 'PBT doubleshot' },
  },
  {
    id: 'prod-headset-stand',
    name: 'Silent Forge Headset Dock',
    category: 'desk-gear',
    franchise: 'Nidavellir Forge',
    description: 'Weighted aluminum dock that keeps the headset line clean between matches.',
    price: 1799,
    compareAtPrice: 2299,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 109,
    stock: 21,
    tags: ['Aluminum', 'Setup', 'headset', ALSO_LIKE_TAG],
    imageUrl: GALLERY[8],
    isLimitedDrop: false,
    specifications: { Base: 'Weighted aluminum', Height: '28 cm' },
  },
  {
    id: 'prod-wrist-rest',
    name: 'Forge Line Wrist Rest',
    category: 'desk-gear',
    franchise: 'Nidavellir Forge',
    description: 'Memory-foam wrist rest with stitched cover matching Runestone mats.',
    price: 999,
    compareAtPrice: 1399,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 87,
    stock: 40,
    tags: ['Wrist', 'Setup', 'Keyboard'],
    imageUrl: GALLERY[2],
    isLimitedDrop: false,
    specifications: { Length: '360 mm', Fill: 'Memory foam' },
  },
  {
    id: 'prod-cable-kit',
    name: 'Clean Desk Cable Kit',
    category: 'desk-gear',
    franchise: 'Pixel Circuit',
    description: 'Braided USB-C / USB-A set with magnetic clips and under-desk anchors.',
    price: 1499,
    compareAtPrice: 1899,
    currency: 'INR',
    rating: 4.4,
    reviewCount: 132,
    stock: 55,
    tags: ['Cable', 'Setup', 'USB-C'],
    imageUrl: GALLERY[15],
    isLimitedDrop: false,
    specifications: { Lengths: '1 m / 2 m', Finish: 'Braided black' },
  },
  {
    id: 'prod-mousepad-pro',
    name: 'Void Control Mousepad',
    category: 'desk-gear',
    franchise: 'Void League',
    description: 'Medium control pad with dense foam core — consistent glide for aim work.',
    price: 1299,
    compareAtPrice: 1699,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 268,
    stock: 44,
    tags: ['Mousepad', 'Control', 'deskmat', ALSO_LIKE_TAG],
    imageUrl: GALLERY[16],
    isLimitedDrop: false,
    specifications: { Size: '450 × 400 mm', Surface: 'Control weave' },
  },
  {
    id: 'prod-monitor-light',
    name: 'Harbor Bar Monitor Light',
    category: 'desk-gear',
    franchise: 'Neon Harbor',
    description: 'Screenbar light with asymmetric beam — no glare on glossy panels.',
    price: 3499,
    compareAtPrice: 4299,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 76,
    stock: 19,
    tags: ['Light', 'Setup', 'Monitor'],
    imageUrl: GALLERY[17],
    isLimitedDrop: false,
    specifications: { Clamp: '10–32 mm', CCT: '2700–6500 K' },
  },
  {
    id: 'prod-controller-grip',
    name: 'Arena Soft Controller Grips',
    category: 'desk-gear',
    franchise: 'Arena Masters',
    description: 'Textured silicone grips for dualsense-style controllers — sweat-ready.',
    price: 599,
    compareAtPrice: 899,
    currency: 'INR',
    rating: 4.3,
    reviewCount: 154,
    stock: 90,
    tags: ['Controller', 'Grip', 'accessory'],
    imageUrl: GALLERY[3],
    isLimitedDrop: false,
    specifications: { Fit: 'Dualsense-style', Material: 'Silicone' },
  },

  // —— Limited drops ——
  {
    id: 'prod-controller-stand',
    name: 'Forged Controller Stand',
    category: 'limited-drops',
    franchise: 'Arena Masters',
    description: 'Metal display stand for controllers, headsets, and signed gear — Drop 02 run.',
    price: 1899,
    compareAtPrice: 2499,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 71,
    stock: 9,
    tags: ['Metal Build', 'Drop 02', 'controller', ALSO_LIKE_TAG],
    imageUrl: GALLERY[3],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 02', Finish: 'Brushed steel' },
  },
  {
    id: 'prod-drop-tee',
    name: 'Echo Line Tee',
    category: 'limited-drops',
    franchise: 'Arena Masters',
    description: 'Short-run heavyweight tee. One colorway, one window.',
    price: 1499,
    compareAtPrice: 1999,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 57,
    stock: 14,
    tags: ['Tee', 'Drop 03'],
    imageUrl: GALLERY[9],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 03', Colorway: 'Echo Black' },
  },
  {
    id: 'prod-mythic-blade',
    name: 'Mythic Edge Desk Blade',
    category: 'limited-drops',
    franchise: 'Mythic Realms',
    description: 'Letter-opener scale prop blade with etched runes and display sheath.',
    price: 3999,
    compareAtPrice: 4999,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 38,
    stock: 6,
    tags: ['Prop', 'Numbered', 'Drop 04', ALSO_LIKE_TAG],
    imageUrl: GALLERY[0],
    isLimitedDrop: true,
    specifications: { Edition: '01 / 250', Length: '28 cm' },
  },
  {
    id: 'prod-void-jacket',
    name: 'Void Night Coach Jacket',
    category: 'limited-drops',
    franchise: 'Void League',
    description: 'Water-resistant coach jacket with reflective mark — booth-to-street layer.',
    price: 4599,
    compareAtPrice: 5499,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 29,
    stock: 11,
    tags: ['Jacket', 'Drop 05', 'Reflective'],
    imageUrl: GALLERY[1],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 05', Shell: 'Water-resistant' },
  },
  {
    id: 'prod-pixel-cart',
    name: 'Circuit Cart Pin Set',
    category: 'limited-drops',
    franchise: 'Pixel Circuit',
    description: 'Five enamel pins on a numbered backing card — Drop 06 soft goods.',
    price: 899,
    compareAtPrice: 1299,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 112,
    stock: 0,
    tags: ['Pins', 'Enamel', 'Drop 06', 'gift'],
    imageUrl: GALLERY[14],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 06', Count: '5 pins' },
  },
  {
    id: 'prod-harbor-tote',
    name: 'Harbor Night Tote',
    category: 'limited-drops',
    franchise: 'Neon Harbor',
    description: 'Heavy canvas tote with interior laptop sleeve — Drop 07 travel piece.',
    price: 1799,
    compareAtPrice: 2299,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 48,
    stock: 17,
    tags: ['Tote', 'Drop 07', 'Travel'],
    imageUrl: GALLERY[13],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 07', Sleeve: '15″ laptop' },
  },
  {
    id: 'prod-forge-bundle',
    name: 'Desk Forge Starter Bundle',
    category: 'limited-drops',
    franchise: 'Nidavellir Forge',
    description: 'Matched deskmat + wrist rest + cable clips in one numbered sleeve.',
    price: 4999,
    compareAtPrice: 6499,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 33,
    stock: 8,
    tags: ['Bundle', 'Setup', 'deskmat', 'Drop 08', ALSO_LIKE_TAG],
    imageUrl: GALLERY[2],
    isLimitedDrop: true,
    specifications: { Edition: 'Drop 08', Includes: 'Mat + rest + clips' },
  },
];

export const demoProducts: Product[] = seeds.map((seed, index) =>
  completeProduct(seed, [
    GALLERY[(index + 1) % GALLERY.length]!,
    GALLERY[(index + 3) % GALLERY.length]!,
    GALLERY[(index + 5) % GALLERY.length]!,
  ]),
);

export const demoMarketplaceOverview: MarketplaceOverview = {
  products: demoProducts,
  featuredProductId: 'prod-odin-statue',
  cart: [
    { productId: 'prod-odin-statue', quantity: 1 },
    { productId: 'prod-rgb-mat', quantity: 1 },
  ],
  latestOrder: {
    id: 'ORD-NDV-1048',
    status: 'packed',
    total: 7798,
    currency: 'INR',
    estimatedDelivery: '2026-08-12',
    itemCount: 2,
  },
};
